# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
  SERVICE_ACCOUNT: ${{ secrets.DEV_SERVICE_ACCOUNT }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job_id:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ env.SERVICE_ACCOUNT }}
      
    - id: 'SetupCloudSDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    - id: 'list-all-files'
      run: 'ls -ltrh'
      
    - id : 'Infrastructure-Manager-Deployment'
      run: 'gcloud infra-manager deployments apply projects/<project_id>/locations/us-central1/deployments/inframanager     --service-account ${{ env.SERVICE_ACCOUNT }}     --local-source="."'
    